#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use /set or similar command to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/quickstart
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_file = ""
salt = on

[data]
__passphrase__ = on
freenode_password = "ABC881E028205DC3789A12342CA27F11DBF5E3FE51C0A4E6227BBD6FB361F7BF8005AE098B2F9CCF8D660C8476F06FD9B1B4CBFB"
